name: 'Terraform'
 
on:
  push:
    branches:
    - main
  pull_request:
  
  workflow_dispatch:
      inputs:
        action:
          description: Action
          required: true
          default: create
          options:
            - create
            - destroy

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      HELM_EXPERIMENTAL_OCI: 1
      HELM_VERSION_TO_INSTALL: 3.5.0
      ACR_NAME: acrtest1407
      ACR_REPO_NAME: becse/shap/mule/chart/hello-world

    runs-on: ubuntu-latest
    outputs:
      QUE_JOB: ${{ steps.github-workflow.outputs.QUE_JOB }}
    environment: production
 
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant 'raminzenithyahooco.onmicrosoft.com'
          az group list
    
    - name: github-workflow
      id: github-workflow
      shell: pwsh
      run: |
        $list = gh run list
        echo "QUE_JOB=$list" >> $env:GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"
 
    #- name: 'Terraform Validate'
      #uses: hashicorp/terraform-github-actions@master
      #with:
        #tf_actions_version: 0.14.8
        #tf_actions_subcommand: 'validate'
        #tf_actions_working_dir: "./terraform"
         
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./terraform"
 
    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./terraform"
        
  Nextflow:
    name: 'Nextflow'
    needs: terraform
    runs-on: ubuntu-latest
    environment: production
    

    steps:
    - name: Echo Variables
      shell: pwsh
      run: |
        echo "${{ env.QUE_JOB }}"
        $list = "${{ env.QUE_JOB }}"
        $list
      env:
        QUE_JOB : ${{ needs.terraform.outputs.QUE_JOB }}
        